pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('java-hello-world') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('java-hello-world') {
                    sh 'mvn test'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'java-hello-world/target/*.jar', fingerprint: true
        }
        success {
            echo 'Build successful!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}

